<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Post;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function countVotesByPost(Post $post, $up = true){
        return $this->createQueryBuilder('v')
                    ->select('COUNT(v.id)')
                    ->where('v.post = :post')
                    ->andWhere('v.up = :up')
                    ->setParameter('post', $post)
                    ->setParameter('up', $up)
                    ->getQuery()->getSingleScalarResult();
    }

    public function removeVotesByUserAndPost(UserInterface $user, Post $post){
        return 1 ==
        $this->createQueryBuilder('v')
             ->delete()
             ->where('v.user = :user')
             ->andWhere('v.post = :post')
             ->setParameter('user', $user)
             ->setParameter('post', $post)
             ->getQuery()->getSingleScalarResult();
    }
}
