# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        in_memory:
#            memory: ~
        users:
            entity: { class: AppBundle\Entity\User, property: username }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false

        api:
            pattern: ^/api
            anonymous: ~
            http_basic: ~
            provider: users

        main:
            pattern: ^/
            anonymous: ~
            http_basic: ~
            provider: users
            form-login:
                login_path: /login
                check_path: /login
                failure_path: /login
                #post_only:      true
                remember_me: true
            logout:
                path: logout
                target: /
            remember_me:
                secret: "%secret%"
                lifetime: 604800 # 1 week
                path:     /
            # activate different ways to authenticate

    access_control:
        - { path: ^/api, roles: ROLE_USER }

    encoders:
        AppBundle\Entity\User: bcrypt
