
index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

register:
    path:     /register
    defaults: { _controller: AppBundle:User:register }

login:
    path:     /login
    defaults: { _controller: AppBundle:User:login }

logout:
    path:     /logout
    defaults: { _controller: AppBundle:User:logout }


comment:
    path:     /comment/{post}
    defaults: { _controller: AppBundle:Comment:comment }
    requirements:
        post: '\d+'


api_post_list:
    path:     /api/posts
    defaults: { _controller: AppBundle:Api\Post:list }
    methods:  [GET]

api_post_get:
    path:     /api/posts/{id}
    defaults: { _controller: AppBundle:Api\Post:get }
    methods:  [GET]