
index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

register:
    path:     /register
    defaults: { _controller: AppBundle:User:register }

login:
    path:     /login
    defaults: { _controller: AppBundle:User:login }

logout:
    path:     /logout
    defaults: { _controller: AppBundle:User:logout }


comment:
    path:     /comment/{post}
    defaults: { _controller: AppBundle:Comment:comment }
    requirements:
        post: '\d+'
