AppBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        message:
            type: string
            length: '140'
        datePost:
            type: datetimetz
    manyToOne:
        user:
            targetEntity: User
        post:
            targetEntity: Post
            inversedBy: comments
    lifecycleCallbacks: {  }
