AppBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: '30'
        datePost:
            type: datetimetz
    oneToOne:
        image:
            targetEntity: Image
            cascade: ["persist", "merge"]
    manyToOne:
        user:
            targetEntity: User
    lifecycleCallbacks: {  }
